### ISSUE TITLE
"Unexpected (" and "Missing parameter name" errors.

### ISSUE THREAD

**Issue by akama-aka** [fastify/middie#214]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

8.3.1

### Stopped working in version

8.3.2

### Node.js version

20.13.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

23H2

### 💥 Regression Report

Error if I use
```js
fastify.use(['/css/(*.css)','/js/(*.js)','/fonts/(*.ttf)'], serveStatic(path.join(__dirname+'/assets')))
```

```cml
TypeError: Unexpected ( at 5, expected END: https://git.new/pathToRegexpError
    at Iter.consume (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:136:15)
    at consume (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:193:16)
    at parse (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:197:20)
    at C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:308:74
    at Array.map (<anonymous>)
    at pathToRegexp (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:308:25)
    at Object.use (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\@fastify\middie\lib\engine.js:23:26)
    at Object.use (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\@fastify\middie\index.js:55:21)
    at module.exports (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\server.js:22:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

and Error if I use 
```js
fastify.use(['/css/*.css','/js/*.js','/fonts/*.ttf'], serveStatic(path.join(__dirname+'/assets')))
```
```cml
TypeError: Missing parameter name at 8: https://git.new/pathToRegexpError
    at name (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:85:19)
    at lexer (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:103:27)
    at lexer.next (<anonymous>)
    at Iter.peek (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:119:38)
    at Iter.tryConsume (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:125:28)
    at Iter.text (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:141:30)
    at consume (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:166:29)
    at parse (C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:197:20)
    at C:\Users\App15a2\WebstormProjects\akami-solutions_cgi\node_modules\path-to-regexp\dist\index.js:308:74
    at Array.map (<anonymous>)
```

It looks like since the latest “minor” version of path-to-regexp some features have been removed which caused major problems, at least for me. 

### Steps to Reproduce

1. Create a server.js File with content like this:

```js
const {createReadStream,readFile} = require('node:fs');
const {join,basename,normalize,resolve } = require("node:path");
const serveStatic = require("serve-static");
const path = require("node:path");

module.exports = async function (fastify, opts) {
    let path_name = process.env.PATH_IDENTIFIER;
    await fastify.register(require('@fastify/middie'))
    const path = require('node:path')
    const serveStatic = require('serve-static')
    fastify.use(['/css/(*.css)','/js/(*.js)','/fonts/(*.ttf)'], serveStatic(path.join(__dirname+'/assets')))
    fastify.get(`/${path_name}/css/:asset`, (req, rep) => {
        const reg = /\.css$/.test(req.params.asset)
        if (!reg) {
            return false;
        }
        let asset = basename(req.params.asset);
        let filePath = normalize(join(__dirname, '/assets/css/', asset));
        let basePath = resolve(__dirname, 'assets/css');

        if (filePath.indexOf(basePath) !== 0) {
            rep.status(403).send('Forbidden');
        } else {
            const stream = createReadStream(filePath, 'utf8');
            rep.headers({
                "Content-Type": "text/css",
                "Cache-Control": "public, max-age=2592000",
                "Pragma":"public,max-age=2592000",
            }).send(stream || null);
        }
    })
}
```

2. Start the project with fastify start file.js
3. You get the error

### Expected Behavior

It should not get any errors and integrate the files.

**Comment by climba03003** [comment]
Since it is related to security, we must bump the version in the same release line.
I have no idea how we can revert to the previous behavior.

**Comment by akama-aka** [comment]
> Since it is related to security, we must bump the version in the same release line. I have no idea how we can revert to the previous behavior.
> 
> Reverting the to previous old version of `path-to-regexp` is not an option.

Okay hm 🤔. Is there a fix for this that I can make myself or so that it works again?

**Comment by climba03003** [comment]
Can you locally test https://github.com/pillarjs/path-to-regexp/tree/v6.3.0 which is recently published?
If everything is ok I will use that version in `8.x` release line so the breaking is not that much.

But it will be `8.x` version for `path-to-regexp` in the `9.x` release line.

**Comment by akama-aka** [comment]
In Version 6.3.0 I get this error

```cml
TypeError: keys.push is not a function
```

**Comment by climba03003** [comment]
Consider the below one as workaround.
```
fastify.use(['/css/*name{.css}', '/js/*name{.js}', '/fonts/*name{.tff}'], serveStatic(path.join(__dirname+'/assets')))
```

**Comment by akama-aka** [comment]
Yes this worked.

**Comment by climba03003** [comment]
I think it is good to reduce impact for most users.
So, I consider https://github.com/fastify/middie/pull/215 is the solution.
You may need to use the old styles once that PR is published.

Sorry for the disturb.

**Comment by akama-aka** [comment]
Okay thank you and all good ^^
