### ISSUE TITLE
Error: fastify-plugin: middie - expected '>=3.0.0' fastify version, '2.12.1' is installed

### ISSUE THREAD

**Issue by moeinrahimi** [fastify/middie#41]
## To Reproduce

```js
yarn add middie

const fastify = require('fastify')({
  logger: true
})

fastify.register(require('middie'))
    throw new Error(`fastify-plugin: ${pluginName} - expected '${version}' fastify version, '${fastifyVersion}' is installed`)
    ^

Error: fastify-plugin: middie - expected '>=3.0.0' fastify version, '2.12.1' is installed
    at checkVersion (E:\projects\karafs\diet-server-v2\node_modules\middie\node_modules\fastify-plugin\plugin.js:67:11)
    at plugin (E:\projects\karafs\diet-server-v2\node_modules\middie\node_modules\fastify-plugin\plugin.js:36:5)
    at Object.<anonymous> (E:\projects\karafs\diet-server-v2\node_modules\middie\index.js:67:18)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\projects\karafs\diet-server-v2\app.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47```

## Expected behavior

A clear and concise description of what you expected to happen.

```js
// Paste the expected results here
```

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=2.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
You should use the upcoming v3 version of Fastify. https://medium.com/@fastifyjs/fastify-v3-rc1-is-here-e804fe18cb0e
